version: "3.8"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

services:
  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: prometheus
    user: ${PUID}:${PGID}
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONF_DIR}/prometheus:/prometheus
      - ${CONF_DIR}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - traefik_proxy
    expose:
      - 9090
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.entrypoints=https"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.$MEELSNET_DOMAIN`)"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.http.routers.prometheus.middlewares=chain-oauth@file"
      - "traefik.http.routers.prometheus.service=prometheus"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

    depends_on:
      - node-exporter
      - cadvisor
  
  node-exporter:
    image: prom/node-exporter:v1.8.0
    container_name: node-exporter
    user: ${PUID}:${PGID}
    restart: unless-stopped
    command:
      - --path.procfs=/host/proc
      - --path.rootfs=/rootfs
      - --path.sysfs=/host/sys
      - --collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)
      - --collector.textfile.directory=/rootfs/var/lib/node_exporter/textfile_collector
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    networks:
      - traefik_proxy
    expose:
      - 9100

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.49.1
    container_name: cadvisor
    restart: unless-stopped
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - traefik_proxy
    expose:
      - 8080

  alertmanager:
    image: prom/alertmanager:v0.27.0
    container_name: alertmanager
    restart: unless-stopped
    command:
    - --config.file=/config/alertmanager.yml
    volumes:
    - ${CONF_DIR}/alertmanager/config:/config
    - ${CONF_DIR}/alertmanager/data:/data
    ports:
    - 9093:9093