version: "3.7"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

services:
  homeassistant-josien:
    container_name: homeassistant-josien
    image: "ghcr.io/home-assistant/home-assistant:2024.4.4"
    privileged: true
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONF_DIR}/homeassistant-josien/config:/config
      - /etc/localtime:/etc/localtime:ro
    networks:
      - traefik_proxy
    ports:
      - 8123:8123
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homeassistant-josien.entrypoints=https"
      - "traefik.http.routers.homeassistant-josien.rule=Host(`thuis.$MEELSNET_DOMAIN`)"
      - "traefik.http.routers.homeassistant-josien.tls=true"
      - "traefik.http.routers.homeassistant-josien.middlewares=chain-no-auth@file"
      - "traefik.http.routers.homeassistant-josien.service=homeassistant-josien"
      - "traefik.http.services.homeassistant-josien.loadbalancer.server.port=8123"
