version: "3.7"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

services:
  unmanic:
    image: josh5/unmanic:0.2.7
    container_name: unmanic
    restart: unless-stopped
    cpus: 1
    mem_limit: 1G
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${CONF_DIR}/unmanic/config:/config
      - ${MEDIA_DIR}:/data
      - ${CONF_DIR}/unmanic/cache:/tmp/unmanic
    networks:
      - traefik_proxy
    expose:
      - 8888
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.unmanic.entrypoints=https"
      - "traefik.http.routers.unmanic.rule=Host(`unmanic.$MEELSNET_DOMAIN`)"
      - "traefik.http.routers.unmanic.tls=true"
      - "traefik.http.routers.unmanic.middlewares=chain-oauth@file"
      - "traefik.http.routers.unmanic.service=unmanic"
      - "traefik.http.services.unmanic.loadbalancer.server.port=8888"
    devices:
      - /dev/dri:/dev/dri
