# MDNS Repeater

services:
  mdns-repeater:
    container_name: mdns-repeater
    image: monstrenyatko/mdns-repeater
    restart: unless-stopped
    profiles: ["other", "all"]
    # command: ip a > /dev/stdout
    command: mdns-repeater-app -f enp1s0 br-c10a265f4312
    network_mode: "host"
