services:
  firefly:
    container_name: firefly
    image: fireflyiii/core:version-6.1.25
    restart: unless-stopped
    profiles: ["other", "all"]
    networks:
      - t3_proxy
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_CONNECTION=pgsql
      - DB_DATABASE=$FIREFLY_DBNAME
      - DB_USERNAME=$FIREFLY_DBUSER
      - DB_PASSWORD=$FIREFLY_DBPASS
    volumes:
      - $CONF_DIR/firefly/upload:/var/www/html/storage/upload
    expose:
      - 8080
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.firefly-rtr.tls=true"
      - "traefik.http.routers.firefly-rtr.entrypoints=websecure"
      - "traefik.http.routers.firefly-rtr.rule=Host(`firefly.$DOMAINNAME_1`)"
      - "traefik.http.routers.firefly-rtr.middlewares=chain-oauth@file"
      - "traefik.http.routers.firefly-rtr.service=firefly-svc"
      - "traefik.http.services.firefly-svc.loadbalancer.server.port=8080"