services:
  plex:
    image: plexinc/pms-docker:plexpass
    container_name: plex
    restart: unless-stopped
    profiles: ["media", "all"]
    networks:
      - t3_proxy
    secrets:
      - plex_claim_token
    environment:
      - PGID=$PGID
      - PUID=$PUID
      - TZ=$TZ
      - PLEX_CLAIM=/run/secrets/plex_claim_token
    volumes:
      - $CONF_DIR/plex/config:/config
      - $CONF_DIR/plex/data:/data
      - $CONF_DIR/plex/deb:/debi
      - $CONF_DIR/plex/dvr:/dvr
      - $CONF_DIR/plex/transcode:/transcode
      - $MEDIA_DIR/TV:/data/tv
      - $MEDIA_DIR/Movies:/data/movies
      - $MEDIA_DIR/Series:/data/series
      - $MEDIA_DIR/Animation:/data/animation
      - $MEDIA_DIR/Anime:/data/anime
      - "$CLOUD_DIR/rick/files/Documents/Personal/3D prints:/data/3d-prints"
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 32469:32469
      - 3005:3005
      - 8324:8324
      - 32469:32469/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    expose:
      - 32400
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.plex-rtr.tls=true"
      - "traefik.http.routers.plex-rtr.entrypoints=websecure"
      - "traefik.http.routers.plex-rtr.rule=Host(`plex.$DOMAINNAME_1`)"
      - "traefik.http.routers.plex-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.plex-rtr.service=plex-svc"
      - "traefik.http.services.plex-svc.loadbalancer.server.port=32400"
    devices:
      - /dev/dri:/dev/dri
