version: "3.7"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

services:
  tautulli:
    image: tautulli/tautulli:v2.14.3
    container_name: tautulli
    restart: unless-stopped
    cpus: 1
    mem_limit: 1G
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${CONF_DIR}/tautulli/config:/config
      - ${CONF_DIR}/plex/config/Library/Application\ Support/Plex\ Media\ Server/Logs:/logs:ro
    networks:
      - traefik_proxy
    expose:
    - 8181
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tautulli.entrypoints=https"
      - "traefik.http.routers.tautulli.rule=Host(`tautulli.$MEELSNET_DOMAIN`)"
      - "traefik.http.routers.tautulli.tls=true"
      - "traefik.http.routers.tautulli.middlewares=chain-no-auth@file"
      - "traefik.http.routers.tautulli.service=tautulli"
      - "traefik.http.services.tautulli.loadbalancer.server.port=8181"
