version: "3.7"

networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge

services:
  prowlarr:
    image: linuxserver/prowlarr:1.20.1
    container_name: prowlarr
    restart: unless-stopped
    cpus: 1
    mem_limit: 1G
    environment:
      - PGID=${PGID}
      - PUID=${PUID}
      - TZ=${TZ}
    volumes:
      - ${CONF_DIR}/prowlarr/config:/config
      - ${DOWNLOAD_DIR}:/data
      - ${DOWNLOAD_DIR}:/downloads
    networks:
      - traefik_proxy
    expose:
      - 9696
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.entrypoints=https"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.$MEELSNET_DOMAIN`) || Host(`indexer.$MEELSNET_DOMAIN`)"
      - "traefik.http.routers.prowlarr.tls=true"
      - "traefik.http.routers.prowlarr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.prowlarr.service=prowlarr"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
